[profile.default]
src = "src"
out = "out"
libs = ["lib"]
solc_version = "0.8.13"

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options

# Monad Testnet Configuration
eth-rpc-url="https://testnet-rpc.monad.xyz"
chain_id = 31337 
# chain_id = 10143
